# Generated by Django 2.2 on 2020-11-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('L', 'Live'), ('P', 'Pending'), ('A', 'Archived')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('order', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('SV', 'Survey'), ('DC', 'Discussion'), ('DI', 'Diary')], max_length=2)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Tile')),
            ],
        ),
    ]
